# Generated by Django 2.2.4 on 2019-08-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hero_name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='Date Realeased')),
            ],
        ),
    ]
